export default [
	'Winner One',
	'Winner Two',
	'Winner Three',
	'Winner Four',
	'Winner Five',
	'Winner Six',
	'Winner Seven',
	'Winner Eight',
	'Winner Nine',
	'Winner Ten',
	'Winner Eleven',
	'Winner Twelve',
	'Winner Thirteen',
	'Winner Fourteen',
	'Winner Fifteen',
	'Winner Sixteen',
	'Winner Seventeen',
	'Winner Eighteen',
	'Winner Nineteen',
	'Winner Twenty'
]