export default [
	'Prize One',
	'Prize Two',
	'Prize Three',
	'Prize Four',
	'Prize Five',
	'Prize Six',
	'Prize Seven',
	'Prize Eight',
	'Prize Nine',
	'Prize Ten',
	'Prize Eleven',
	'Prize Twelve',
	'Prize Thirteen',
	'Prize Fourteen',
	'Prize Fifteen',
	'Prize Sixteen',
	'Prize Seventeen',
	'Prize Eighteen',
	'Prize Nineteen',
	'Prize Twenty'
]